import { test, expect } from '@playwright/test'

test('встреча → назначения → фиксация → личный расчёт → возвраты', async ({ page, browser }) => {
  await page.goto('/')
  await page.getByLabel('Email', { exact: true }).fill('browser@example.test')
  await page.getByLabel('Пароль', { exact: true }).fill('проверочный-пароль-123')
  await page.getByRole('button', { name: 'Создать аккаунт', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Мои встречи' })).toBeVisible()
  await page.getByLabel('Название', { exact: true }).fill('Вечер с друзьями')
  await page.getByLabel('Дата', { exact: true }).fill('2026-09-16')
  await page.getByRole('button', { name: 'Создать встречу', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Вечер с друзьями' })).toBeVisible()
  for (const name of ['Женя', 'Дима']) {
    await page.getByLabel('Новый участник').fill(name)
    await page.getByRole('button', { name: 'Добавить участника', exact: true }).click()
  }
  await page.getByLabel('Кто оплатил весь чек').selectOption({ label: 'Женя' })
  await page.getByRole('button', { name: 'Добавить позицию', exact: true }).click()
  const personal = page.locator('article.card').nth(0)
  await personal.getByLabel('Название позиции').fill('Личный рамен')
  await personal.getByLabel('Цена за единицу, ₽').fill('100')
  await personal.getByLabel('Распределение').selectOption('single')
  await personal.getByRole('button', { name: 'Женя', exact: true }).click()
  await page.getByRole('button', { name: 'Добавить позицию', exact: true }).click()
  const shared = page.locator('article.card').nth(1)
  await shared.getByLabel('Название позиции').fill('Общая пицца')
  await shared.getByLabel('Цена за единицу, ₽').fill('100')
  await shared.getByRole('button', { name: 'На всех', exact: true }).click()
  await page.getByLabel('Итог на ресторанном чеке, ₽').fill('200')
  await page.getByRole('button', { name: 'Сохранить и пересчитать', exact: true }).click()
  await expect(page.getByRole('status')).toHaveText('Изменения сохранены')
  await expect(page.getByRole('button', { name: 'Зафиксировать расчёт' })).toBeEnabled()
  await page.getByRole('button', { name: 'Зафиксировать расчёт' }).click()
  await expect(page.getByText('Зафиксированный расчёт', { exact: true })).toBeVisible()
  const dimas = page.locator('.total-row').filter({ has: page.getByRole('heading', { name: /Дима/ }) })
  await dimas.getByRole('button', { name: 'Создать новую ссылку' }).click()
  const url = await dimas.getByRole('link', { name: 'Открыть персональный расчёт' }).getAttribute('href')
  expect(url).toBeTruthy()
  const guestContext = await browser.newContext()
  const guest = await guestContext.newPage()
  await guest.goto(url!)
  await expect(guest.getByText('Общая пицца', { exact: false })).toBeVisible()
  await expect(guest.getByText('Личный рамен', { exact: false })).toHaveCount(0)
  await expect(guest.getByRole('heading', { name: /Осталось вернуть: 50,00/ })).toBeVisible()
  await page.getByLabel('Кто перевёл').selectOption({ label: 'Дима' })
  await page.getByLabel('Получено, ₽').fill('20')
  await page.getByRole('button', { name: 'Записать перевод', exact: true }).click()
  await expect(page.locator('.payment-row')).toHaveCount(1)
  await guest.reload()
  await expect(guest.getByRole('heading', { name: /Осталось вернуть: 30,00/ })).toBeVisible()
  await page.getByLabel('Получено, ₽').fill('30')
  await page.getByRole('button', { name: 'Записать перевод', exact: true }).click()
  await expect(page.locator('.payment-row')).toHaveCount(2)
  await guest.reload()
  await expect(guest.getByRole('heading', { name: /Осталось вернуть: 0,00/ })).toBeVisible()
  await page.getByRole('button', { name: 'Закрыть встречу', exact: true }).click()
  await expect(page.getByText('Встреча закрыта', { exact: true })).toBeVisible()
  await expect(page.locator('body')).not.toHaveJSProperty('scrollWidth', 0)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/prototype-mobile.png', fullPage: true })
  await guestContext.close()
})
